### PR TITLE
Tidy layout

### PR DESCRIPTION
**Pull request by hturner**
In this PR I have

- improved the layout, in particular placing the signature block at the bottom so the signature does not overlap with the watermark
- implemented a multi-colour border (magma palette). This is in fact a background image, so we now have 4 layers: the multi-coloured background, a white background, the watermark and the text. This required a custom `pdf_document()` template without the scaling of graphics enforced when using the default template. On the plus side, we can now scale the watermark within the box, so the `partly_transparent_forwards_borders.png` is no longer needed (I have left it in the assets for now).

Commit 60ce946 has a solid border version, which i tried with dark grey, light grey and purple, but I preferred the multi-coloured version so just left that in a separate commit for reference.

I have used the version from 3a25053 to produce the certificate we wanted right now.

### CODE REVIEW

**Comment by maelle** [comment]
Very cool!

Could you add a PDF example before merging? Then we could link it from the README (I now realize my example code in the README might already be outdated...) so that people see how it'll look like?

**Comment by hturner** [comment]
Rebased on master and added example output from README code - which still works fine by the way! 

Picked up a small bug in my previous edits to clean up intermediate files on exit, so also fixed this.

**Comment by maelle** [comment]
Awesome!

**Comment by maelle** [comment]
The certificate looks so good 🌟

**Pull request merged**
